### ISSUE TITLE
0.7.0 Release To-do

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/concurrent-ruby#98]
This is the to-do list for the 0.7.0 release. The target date for this release is Sunday, 10 August, 2014. This is intended to coincide with the [Steel City Ruby](http://www.steelcityruby.org/) conference being help in Pittsburgh, PA, USA on 15-16 August. This is an initial list based on the discussion in Issue #83 ("v0.7.0, GitHub Organization, and Merging Atomic"). Please feel free to add/edit/delete items as necessary.
## Organization
- [x] Create a GitHub organization
- [x] Move this repo to the new organization
- [x] Move the https://github.com/headius/ruby-atomic ruby repo to the new organization
- [x] Update DNS for http://concurrent-ruby.com
- [x] Update links in Rubygems.org
## Native Extensions
- [x] Setup the gemspec and extconf.rb files to support C extensions (based on ruby-atomic and the experimental CRuby branches)
- [x] Setup the gemspec and extconf.rb files to support pure Java extensions (based on ruby-atomic)
- [x] Update experimental CRuby extensions based on ruby-atomic
  - [x] Remove CEvent (poor performance)
  - [x] Move extensions to root of `ext` folder
  - [x] Use `have_header` to set `#define`
  - [x] Update _extsonf.rb_ to support multiple operating systems
  - [x] Update `CAtomicBoolean` to support multiple operating systems
  - [x] Update `CAtomicFixnum` to support multiple operating systems
  - [x] Merge native extension branches into master
- [x] Merge ruby-atomic
  - [x] Verify compatibility of pure-Ruby, Java, and CRuby versions
  - [x] Move classes into the Concurrent module
  - [x] Rename classes/modules to match existing conventions
- [ ] ~~Add FreeBSD to automated build~~ (reconsider)
## New and Updated Abstractions
- [x] Either deprecate `Supervisor` and `Runnable` or update them to use executors and be more thread safe
- [ ] ~~Implement fork-join~~ (move to future release)
- [ ] ~~native `JavaEvent`~~ (move to future release)
## Tests
- [x] Update RSpec to 3.x
- [ ] Replace all `sleep` calls in specs with deterministic locking (using `CountDownLatch` or other atomic variable)
- [ ] Update tests to use `ImmediateExecutor` when possible
- [x] Fix brittle specs (see Issue #97)
- [ ]  Create stress tests for core classes including
  - [ ] Thread pools
## Actor
- [x] fix pending and deadlocking tests
- [x] better documentation
- [x] mention add Algebrick and Hamster for messaging
- [x] **0.6.1** release
- [x] update old actress gem to point here
- [x] basic supervision and restarts (`:terminate!`, `:resume!`, `:reset!`, `:restart!`) #132
- [x] restart strategies (`:one_for_one`, `:one_for_all`) #132 
- [x] dead letter routing #132
- [x] actor state monitoring as in Akka #132
- [x] Remove old `Actor` class
- [x] Rename `Actress` to `Actor` #132 
- [x] Create `Actress`/`Actor` alias #132
- [ ] better tests
- [ ] add examples to documentation
- [ ] add example of using Actors with Algebrick and Hamster
- [ ] **0.7** release
- [ ] Remote actors using DRb
- [ ] IO interoperation
- [ ] un/become
- [ ] ~~implement classes similar to Erlang's [gen_server](http://www.erlang.org/doc/man/gen_server.html), [gen_event](http://www.erlang.org/doc/man/gen_event.html), and [gen_fsm](http://www.erlang.org/doc/man/gen_fsm.html) based on supervision.~~ (move to future release)
